version: '2'
services:
  noome-app:
    image: noome
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://noome-postgresql:5432/NooMe
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://noome-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://noome-elasticsearch:9200
    ports:
      - 8080:8080
  noome-postgresql:
    extends:
      file: postgresql.yml
      service: noome-postgresql
  noome-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: noome-elasticsearch
